language: cpp
compiler:
- gcc

before_install:
  - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots
  - sudo apt-get update -qq
  - sudo apt-get install -y libsdl2-dev libglm-dev libboost-all-dev libglew-dev

branches:
  only:
    - master

notifications:
  email: true

# before build script, run autoreconf
before_script: autoreconf -i

os:
- linux
- osx

sudo: true